name = "Astro"
uuid = "c36f77fa-2ac2-45a9-8ce6-465ee13e27d4"
authors = ["Heptazhou <zhou at 0h7z dot com>"]
version = "0.2.1"

[deps]
AstroAngles = "5c4adb95-c1fc-4c53-b4ea-2a94080c53d2"
AstroLib = "c7932e45-9af1-51e7-9da9-f004cd3a462b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"

[compat]
julia = "â‰¥ 1.7"
